// <auto-generated />
using System;
using AgroMulti.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroMulti.Data.Migrations
{
    [DbContext(typeof(AgroMultiContext))]
    partial class AgroMultiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroMulti.Data.Models.Entrega", b =>
                {
                    b.Property<int>("EntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntregaId"));

                    b.Property<int>("Cajas")
                        .HasColumnType("int");

                    b.Property<int>("EstadoEntregaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<decimal>("Kilos")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("KilosSecos")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NombreConductor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroAnaquel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroEntrega")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pasillo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Piso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductorId")
                        .HasColumnType("int");

                    b.Property<int>("Sacos")
                        .HasColumnType("int");

                    b.Property<int?>("SubProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntregaId");

                    b.HasIndex("EstadoEntregaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductorId");

                    b.HasIndex("SubProductoId");

                    b.HasIndex(new[] { "NumeroEntrega" }, "UQ_Entrega_NumeroEntrega")
                        .IsUnique();

                    b.ToTable("Entrega");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.EstadoEntrega", b =>
                {
                    b.Property<int>("EstadoEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoEntregaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoEntregaId");

                    b.ToTable("EstadoEntrega");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.HistoricoEstadoEntrega", b =>
                {
                    b.Property<int>("HistoricoEstadoEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoricoEstadoEntregaId"));

                    b.Property<int>("EntregaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoEntregaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("HistoricoEstadoEntregaId");

                    b.HasIndex("EntregaId")
                        .HasDatabaseName("IX_HistoricoEstadoEntrega_EntregaId");

                    b.HasIndex("EstadoEntregaId");

                    b.HasIndex("FechaCambio")
                        .HasDatabaseName("IX_HistoricoEstadoEntrega_FechaCambio");

                    b.ToTable("HistoricosEstadoEntrega");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.Productor", b =>
                {
                    b.Property<int>("ProductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductorId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductorId");

                    b.HasIndex(new[] { "Codigo" }, "UQ_Productor_Codigo")
                        .IsUnique();

                    b.ToTable("Productor");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.SubProducto", b =>
                {
                    b.Property<int>("SubProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubProductoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("SubProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("SubProducto");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.Entrega", b =>
                {
                    b.HasOne("AgroMulti.Data.Models.EstadoEntrega", "EstadoEntrega")
                        .WithMany("Entregas")
                        .HasForeignKey("EstadoEntregaId")
                        .IsRequired()
                        .HasConstraintName("FK_Entrega_EstadoEntrega");

                    b.HasOne("AgroMulti.Data.Models.Producto", "Producto")
                        .WithMany("Entregas")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_Entrega_Producto");

                    b.HasOne("AgroMulti.Data.Models.Productor", "Productor")
                        .WithMany("Entregas")
                        .HasForeignKey("ProductorId")
                        .IsRequired()
                        .HasConstraintName("FK_Entrega_Productor");

                    b.HasOne("AgroMulti.Data.Models.SubProducto", "SubProducto")
                        .WithMany("Entregas")
                        .HasForeignKey("SubProductoId")
                        .HasConstraintName("FK_Entrega_SubProducto");

                    b.Navigation("EstadoEntrega");

                    b.Navigation("Producto");

                    b.Navigation("Productor");

                    b.Navigation("SubProducto");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.HistoricoEstadoEntrega", b =>
                {
                    b.HasOne("AgroMulti.Data.Models.Entrega", "Entrega")
                        .WithMany("HistoricosEstado")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HistoricoEstadoEntrega_Entrega");

                    b.HasOne("AgroMulti.Data.Models.EstadoEntrega", "EstadoEntrega")
                        .WithMany()
                        .HasForeignKey("EstadoEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HistoricoEstadoEntrega_EstadoEntrega");

                    b.Navigation("Entrega");

                    b.Navigation("EstadoEntrega");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.SubProducto", b =>
                {
                    b.HasOne("AgroMulti.Data.Models.Producto", "Producto")
                        .WithMany("SubProductos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_SubProducto_Producto");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.Entrega", b =>
                {
                    b.Navigation("HistoricosEstado");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.EstadoEntrega", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.Producto", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("SubProductos");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.Productor", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("AgroMulti.Data.Models.SubProducto", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
